export const employeesData = [
  {
    id: 1,
    firstName: 'Sahil',
    lastName: 'Sutariya',
    email: 'sahil@gmail.com',
    salary: '95000',
    birthdate: '2003-05-24',
  },
  {
    id: 2,
    firstName: 'John',
    lastName: 'Doe',
    email: 'john@gmail.com',
    salary: '80000',
    birthdate: '2000-04-17',
  },
  {
    id: 3,
    firstName: 'Vishal',
    lastName: 'Patel',
    email: 'vishal@gmail.com',
    salary: '79000',
    birthdate: '2019-05-01',
  },
  {
    id: 4,
    firstName: 'Kent',
    lastName: 'Rosner',
    email: 'kent@gmail.com',
    salary: '56000',
    birthdate: '2019-05-03',
  },
  {
    id: 5,
    firstName: 'Arsenio',
    lastName: 'Grant',
    email: 'arsenio@gmail.com',
    salary: '65000',
    birthdate: '2019-06-13',
  },
  {
    id: 6,
    firstName: 'Laurena',
    lastName: 'Lurie',
    email: 'laurena@gmail.com',
    salary: '120000',
    birthdate: '2019-07-30',
  },
  {
    id: 7,
    firstName: 'George',
    lastName: 'Tallman',
    email: 'george@gmail.com',
    salary: '90000',
    birthdate: '2019-08-15',
  },
  {
    id: 8,
    firstName: 'Jesica',
    lastName: 'Watlington',
    email: 'jesica@gmail.com',
    salary: '60000',
    birthdate: '2019-10-10',
  },
  {
    id: 9,
    firstName: 'Matthew',
    lastName: 'Warren',
    email: 'matthew@gmail.com',
    salary: '71000',
    birthdate: '2019-10-15',
  },
  {
    id: 10,
    firstName: 'Lyndsey',
    lastName: 'Follette',
    email: 'lyndsey@gmail.com',
    salary: '110000',
    birthdate: '2020-01-15',
  },
];
